source 'https://rubygems.org'
ruby '3.2.2'

gem 'activesupport'
gem 'capybara'
gem 'capybara-screenshot'
gem 'cucumber'
gem 'dotenv', '~> 2.7.5'
gem 'faker', :git => 'https://github.com/stympy/faker.git', :branch => 'main'
gem 'faraday', '1.9.3'
gem 'filesize', '~> 0.2.0'
gem 'geckodriver-helper', '~> 0.0.5'
gem 'headless', '~> 2.3', '>= 2.3.1'
gem 'httparty', '0.17.0'
gem 'json'
gem 'pry'
gem 'rake', '~> 12.3.3'
gem 'report_builder'
gem 'rspec'
gem 'rspec-retry'
gem 'selenium-webdriver'
gem 'sinatra'
gem 'site_prism'
